export const products = [
    {
      id: 1,
      name: "Wireless Bluetooth Headphones",
      category: "Electronics",
      brand: "SoundMagic",
      price: 59.99,
      discount: 10,
      rating: 4.5,
      reviews: 120,
      inStock: true,
      sku: "SM-WH-001",
      images: "https://images.unsplash.com/photo-1741770067276-a10e15ff5197?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      color: "Black",
      size: null,
      description: "High-quality wireless headphones with noise cancellation and long battery life.",
      tags: ["audio", "wireless", "headphones"],
      shipping: "Free Shipping",
      warranty: "1 Year",
      createdAt: "2025-03-01",
      updatedAt: "2025-04-10",
    },
    {
      id: 2,
      name: "Men's Casual Denim Jacket",
      category: "Fashion",
      brand: "UrbanEdge",
      price: 79.99,
      discount: 20,
      rating: 4.2,
      reviews: 87,
      inStock: true,
      sku: "UE-DJ-002",
      images: "https://images.unsplash.com/photo-1579592610812-49855d94db0d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fE1lbidzJTIwQ2FzdWFsJTIwRGVuaW0lMjBKYWNrZXR8ZW58MHx8MHx8fDA%3D",
      color: "Blue",
      size: "L",
      description: "Stylish denim jacket perfect for casual wear in all seasons.",
      tags: ["jacket", "men", "denim"],
      shipping: "Standard",
      warranty: "6 Months",
      createdAt: "2025-02-20",
      updatedAt: "2025-04-05",
    },
    {
      id: 3,
      name: "Smart LED TV 50-inch",
      category: "Electronics",
      brand: "ViewPro",
      price: 499.99,
      discount: 15,
      rating: 4.6,
      reviews: 203,
      inStock: false,
      sku: "VP-TV-050",
      images: "https://images.unsplash.com/photo-1615210230840-69c07c13b4d1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fFNtYXJ0JTIwTEVEJTIwVFYlMjA1MCUyMGluY2h8ZW58MHx8MHx8fDA%3D",
      color: "Black",
      size: "50-inch",
      description: "4K UHD Smart TV with built-in streaming apps and voice control.",
      tags: ["tv", "smart", "led"],
      shipping: "Free Delivery",
      warranty: "2 Years",
      createdAt: "2025-01-15",
      updatedAt: "2025-03-28",
    },
    {
      id: 4,
      name: "Running Shoes",
      category: "Footwear",
      brand: "FastStep",
      price: 89.99,
      discount: 5,
      rating: 4.3,
      reviews: 65,
      inStock: true,
      sku: "FS-RS-004",
      images: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8UnVubmluZyUyMFNob2VzfGVufDB8fDB8fHww",
      color: "Gray",
      size: "10",
      description: "Lightweight and breathable running shoes for men and women.",
      tags: ["shoes", "running", "sports"],
      shipping: "Standard",
      warranty: "1 Year",
      createdAt: "2025-03-05",
      updatedAt: "2025-04-12",
    },
    {
      id: 5,
      name: "Ergonomic Office Chair",
      category: "Furniture",
      brand: "ComfySit",
      price: 199.99,
      discount: 25,
      rating: 4.7,
      reviews: 98,
      inStock: true,
      sku: "CS-OC-005",
      images: "https://plus.unsplash.com/premium_photo-1682432838340-e1001c1d97c8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8RXJnb25vbWljJTIwT2ZmaWNlJTIwQ2hhaXJ8ZW58MHx8MHx8fDA%3D",
      color: "Black",
      size: "Standard",
      description: "Adjustable office chair with lumbar support and breathable mesh back.",
      tags: ["chair", "office", "ergonomic"],
      shipping: "Free Shipping",
      warranty: "3 Years",
      createdAt: "2025-02-28",
      updatedAt: "2025-04-11",
    },
    {
      id: 6,
      name: "Non-stick Cookware Set",
      category: "Home & Kitchen",
      brand: "ChefMate",
      price: 129.99,
      discount: 30,
      rating: 4.4,
      reviews: 150,
      inStock: true,
      sku: "CM-CS-006",
      images: "https://images.unsplash.com/photo-1588279102558-dabc7b32d9b1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Tm9uJTIwc3RpY2slMjBDb29rd2FyZSUyMFNldHxlbnwwfHwwfHx8MA%3D%3D",
      color: "Red",
      size: "12-piece",
      description: "Durable and stylish non-stick cookware set with heat-resistant handles.",
      tags: ["cookware", "kitchen", "non-stick"],
      shipping: "Standard",
      warranty: "1 Year",
      createdAt: "2025-01-30",
      updatedAt: "2025-04-02",
    },
    {
      id: 7,
      name: "Fitness Tracker Watch",
      category: "Wearables",
      brand: "FitBuddy",
      price: 69.99,
      discount: 10,
      rating: 4.1,
      reviews: 78,
      inStock: true,
      sku: "FB-FT-007",
      images: "https://images.unsplash.com/photo-1557935728-e6d1eaabe558?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Rml0bmVzcyUyMFRyYWNrZXIlMjBXYXRjaHxlbnwwfHwwfHx8MA%3D%3D",
      color: "Black",
      size: "Adjustable",
      description: "Track your steps, sleep, heart rate and more with this sleek fitness tracker.",
      tags: ["fitness", "wearable", "tracker"],
      shipping: "Standard",
      warranty: "1 Year",
      createdAt: "2025-03-12",
      updatedAt: "2025-04-09",
    },
    {
      id: 8,
      name: "Gaming Mouse RGB",
      category: "Computers",
      brand: "GameX",
      price: 39.99,
      discount: 15,
      rating: 4.8,
      reviews: 230,
      inStock: true,
      sku: "GX-GM-008",
      images: "https://images.unsplash.com/photo-1616296425622-4560a2ad83de?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8R2FtaW5nJTIwTW91c2UlMjBSR0J8ZW58MHx8MHx8fDA%3D",
      color: "RGB",
      size: null,
      description: "High precision gaming mouse with customizable RGB lighting and DPI settings.",
      tags: ["mouse", "gaming", "rgb"],
      shipping: "Standard",
      warranty: "2 Years",
      createdAt: "2025-01-25",
      updatedAt: "2025-04-07",
    },
    {
      id: 9,
      name: "Stainless Steel Water Bottle",
      category: "Outdoors",
      brand: "EcoSip",
      price: 24.99,
      discount: 5,
      rating: 4.0,
      reviews: 34,
      inStock: true,
      sku: "ES-WB-009",
      images: "https://plus.unsplash.com/premium_photo-1681284938505-62efa3494bf2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8U3RhaW5sZXNzJTIwU3RlZWwlMjBXYXRlciUyMEJvdHRsZXxlbnwwfHwwfHx8MA%3D%3D",
      color: "Silver",
      size: "750ml",
      description: "Leak-proof and insulated water bottle to keep drinks cold or hot.",
      tags: ["bottle", "outdoors", "eco"],
      shipping: "Standard",
      warranty: "1 Year",
      createdAt: "2025-02-10",
      updatedAt: "2025-03-30",
    },
    {
      id: 10,
      name: "Wooden Coffee Table",
      category: "Furniture",
      brand: "RusticLiving",
      price: 149.99,
      discount: 10,
      rating: 4.6,
      reviews: 60,
      inStock: false,
      sku: "RL-CT-010",
      images: "https://plus.unsplash.com/premium_photo-1680098058374-e580a9dbaeef?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8V29vZGVuJTIwQ29mZmVlJTIwVGFibGV8ZW58MHx8MHx8fDA%3D",
      color: "Walnut",
      size: "Medium",
      description: "Elegant wooden coffee table with a natural finish for modern living rooms.",
      tags: ["coffee table", "wood", "furniture"],
      shipping: "Free Shipping",
      warranty: "2 Years",
      createdAt: "2025-01-05",
      updatedAt: "2025-04-01",
    },
    {
        id: 11,
        name: "4-Slice Toaster",
        category: "Home Appliances",
        brand: "ToastPro",
        price: 49.99,
        discount: 10,
        rating: 4.2,
        reviews: 57,
        inStock: true,
        sku: "TP-TST-011",
        images: "https://plus.unsplash.com/premium_photo-1719452894874-3da9fa3b882c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8NCUyMFNsaWNlJTIwVG9hc3RlcnxlbnwwfHwwfHx8MA%3D%3D",
        color: "Silver",
        size: null,
        description: "Compact toaster with browning control and defrost function.",
        tags: ["toaster", "kitchen", "appliances"],
        shipping: "Standard",
        warranty: "1 Year",
        createdAt: "2025-02-05",
        updatedAt: "2025-04-01",
      },
      {
        id: 12,
        name: "Kids Building Blocks Set",
        category: "Toys",
        brand: "BuildFun",
        price: 29.99,
        discount: 5,
        rating: 4.8,
        reviews: 112,
        inStock: true,
        sku: "BF-BB-012",
        images: "https://images.unsplash.com/photo-1638932717348-3b8f19865301?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8S2lkcyUyMEJ1aWxkaW5nJTIwQmxvY2tzJTIwU2V0fGVufDB8fDB8fHww",
        color: "Multicolor",
        size: "300 pieces",
        description: "Creative building block set for kids aged 3+.",
        tags: ["toys", "kids", "blocks"],
        shipping: "Free Shipping",
        warranty: "6 Months",
        createdAt: "2025-03-18",
        updatedAt: "2025-04-12",
      },
      {
        id: 13,
        name: "Laptop Stand Adjustable",
        category: "Accessories",
        brand: "Elevate",
        price: 39.99,
        discount: 20,
        rating: 4.3,
        reviews: 85,
        inStock: true,
        sku: "EV-LS-013",
        images: "https://media.istockphoto.com/id/1731897087/photo/aluminum-laptop-stand-to-improve-ventilation-on-a-white-background-in-isolation.webp?a=1&b=1&s=612x612&w=0&k=20&c=zXVfNtaRWlgktqVK6-vyr5VfPBfQJrEDgATaiZveY54=",
        color: "Gray",
        size: "Universal",
        description: "Foldable and adjustable laptop stand for desks and home office.",
        tags: ["laptop", "accessory", "stand"],
        shipping: "Standard",
        warranty: "1 Year",
        createdAt: "2025-02-18",
        updatedAt: "2025-04-03",
      },
      {
        id: 14,
        name: "Makeup Brush Set",
        category: "Beauty",
        brand: "GlamPro",
        price: 19.99,
        discount: 10,
        rating: 4.5,
        reviews: 143,
        inStock: true,
        sku: "GP-MBS-014",
        images: "https://images.unsplash.com/photo-1736753365978-0b5090f90095?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TWFrZXVwJTIwQnJ1c2glMjBTZXR8ZW58MHx8MHx8fDA%3D",
        color: "Rose Gold",
        size: "10-piece",
        description: "Soft bristle makeup brushes in a travel-friendly pouch.",
        tags: ["beauty", "makeup", "brush"],
        shipping: "Standard",
        warranty: "6 Months",
        createdAt: "2025-01-22",
        updatedAt: "2025-04-08",
      },
      {
        id: 15,
        name: "Camping Tent for 4",
        category: "Outdoors",
        brand: "CampGear",
        price: 149.99,
        discount: 15,
        rating: 4.6,
        reviews: 92,
        inStock: true,
        sku: "CG-CT-015",
        images: "https://images.unsplash.com/photo-1703304862580-206bdf82fbc8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Q2FtcGluZyUyMFRlbnQlMjBmb3IlMjA0fGVufDB8fDB8fHww",
        color: "Green",
        size: "4-person",
        description: "Waterproof tent with quick setup and sturdy build for outdoor adventures.",
        tags: ["camping", "tent", "outdoor"],
        shipping: "Free Delivery",
        warranty: "2 Years",
        createdAt: "2025-03-07",
        updatedAt: "2025-04-10",
      },
      {
        id: 16,
        name: "Wireless Mechanical Keyboard",
        category: "Computers",
        brand: "TypePro",
        price: 89.99,
        discount: 20,
        rating: 4.7,
        reviews: 198,
        inStock: true,
        sku: "TP-KB-016",
        images: "https://images.unsplash.com/photo-1694405145070-e58cc29771fa?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V2lyZWxlc3MlMjBNZWNoYW5pY2FsJTIwS2V5Ym9hcmR8ZW58MHx8MHx8fDA%3D",
        color: "Black",
        size: "Full-size",
        description: "Backlit mechanical keyboard with wireless Bluetooth support.",
        tags: ["keyboard", "mechanical", "wireless"],
        shipping: "Standard",
        warranty: "2 Years",
        createdAt: "2025-02-12",
        updatedAt: "2025-04-06",
      },
      {
        id: 17,
        name: "Blender with Glass Jar",
        category: "Kitchen",
        brand: "SmoothiePro",
        price: 69.99,
        discount: 10,
        rating: 4.4,
        reviews: 73,
        inStock: true,
        sku: "SP-BL-017",
        images: "https://images.unsplash.com/photo-1585237672814-8f85a8118bf6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8QmxlbmRlciUyMHdpdGglMjBHbGFzcyUyMEphcnxlbnwwfHwwfHx8MA%3D%3D",
        color: "White",
        size: "1.5L",
        description: "Powerful blender ideal for smoothies, sauces, and crushing ice.",
        tags: ["blender", "kitchen", "appliance"],
        shipping: "Standard",
        warranty: "1 Year",
        createdAt: "2025-03-01",
        updatedAt: "2025-04-05",
      },
      {
        id: 18,
        name: " ",
        category: "Fitness",
        brand: "ZenFit",
        price: 39.99,
        discount: 5,
        rating: 4.3,
        reviews: 58,
        inStock: true,
        sku: "ZF-YM-018",
        images: "https://images.unsplash.com/photo-1637157216470-d92cd2edb2e8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8WW9nYSUyME1hdCUyMEVjbyUyMEZyaWVuZGx5fGVufDB8fDB8fHww",
        color: "Purple",
        size: "72 x 24 inches",
        description: "Non-slip, eco-friendly yoga mat with extra cushioning.",
        tags: ["yoga", "mat", "fitness"],
        shipping: "Standard",
        warranty: "6 Months",
        createdAt: "2025-02-08",
        updatedAt: "2025-04-04",
      },
      {
        id: 19,
        name: "LED Desk Lamp with USB",
        category: "Home Office",
        brand: "BrightLite",
        price: 34.99,
        discount: 10,
        rating: 4.5,
        reviews: 101,
        inStock: true,
        sku: "BL-DL-019",
        images: "https://images.unsplash.com/photo-1612813434847-b01fffea46ae?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TEVEJTIwRGVzayUyMExhbXAlMjB3aXRoJTIwVVNCfGVufDB8fDB8fHww",
        color: "White",
        size: "Adjustable",
        description: "Touch control LED lamp with adjustable brightness and USB charging port.",
        tags: ["lamp", "desk", "lighting"],
        shipping: "Standard",
        warranty: "1 Year",
        createdAt: "2025-02-25",
        updatedAt: "2025-04-07",
      },
      {
        id: 20,
        name: "Mini Projector Portable",
        category: "Electronics",
        brand: "PocketBeam",
        price: 129.99,
        discount: 25,
        rating: 4.6,
        reviews: 187,
        inStock: true,
        sku: "PB-MP-020",
        images: "https://media.istockphoto.com/id/652812364/photo/portable-working-beamer-projector.webp?a=1&b=1&s=612x612&w=0&k=20&c=DAwNNLCZi7OPJNM8R9btHdsI5N58BE4pfW0D2GIUEfU=",
        color: "Black",
        size: "Mini",
        description: "Portable projector for movies, presentations, and gaming on-the-go.",
        tags: ["projector", "portable", "electronics"],
        shipping: "Free Delivery",
        warranty: "1 Year",
        createdAt: "2025-03-10",
        updatedAt: "2025-04-09",
      }
    // 10 more products...
  ];
  
  // Do you want me to generate the remaining 10 as well?
  